### ISSUE TITLE
Code generator issue on YES,NO,.. 

### ISSUE THREAD

**Issue by CGantert345** [UnionInternationalCheminsdeFer/OSDM#350]
DB: Enum values like "YES" and "NO" confuse some code generators. They create a binary element, even if there are three options (e.g. ExchangeableType has the options YES, NO, WITH_CONDITIONS). The solution is to have the values quoted, i.e. "YES", "NO", "WITH_CONDITIONS".

to be discussed with Andreas for the generator

**Comment by jspetrak** [comment]
yaml is going to be the master source, provide patch for 3.2 for boolean-like enums

**Comment by jonekdahl** [comment]
Hi,

I just ran into this issue when using openapi-generator to generate C# code from OSDM spec version 3.0.4. According to the milestone assignment, this is fixed in the 3.2 version of the spec, but unfortunately I cannot just upgrade, I need to stay on 3.0.x for interoperability with my Swedish counterparts.

Any chance that this could be back-ported to 3.0?

**Comment by jspetrak** [comment]
@jonekdahl Please file an issue for backport to 3.1, 3.0 here at github. We can make it happen

**Comment by jonekdahl** [comment]
@jspetrak Thanks, I created #764 .

**Comment by jspetrak** [comment]
@jonekdahl Thanks, that looks good! I have merged the PR and also created an official release so you can immediately pull the openapi file from Git and use in the project.
