### ISSUE TITLE
What is FulfillmentMediaType when FulfillmentDocument.format is image/png or jpeg?

### ISSUE THREAD

**Issue by jspetrak** [UnionInternationalCheminsdeFer/OSDM#741]
I want to produce Fulfillment containing image with bar code only in JPEG or PNG format.

There isn't suitable FulfillmentMediaType to indicate that I only seek the image with barcode and not complete ticket like `A4_PDF` or `UIC_PDF`.

Do we need a new media type or thse *_PDF media types are suitable?

If yes, suggested value is `BARCODE_IMAGE`, result is FulfillmentDocument in formats `image/jpeg` or `image/png`.

**Comment by jspetrak** [comment]
No, `FULFILLMENT_PARTS` media type must be used and `fulfillmentParts` with `securityFeatures` provided.

**Comment by FloLhomme** [comment]
Hello @jspetrak,

We are right now having the same question you raised back in Nov. 2024. 

First of all, here is our exact situation regarding this matter.

**We must deliver the right of travel in two different formats for our clients.** 
1. The image of the barcode that can be directly used for travelling. 
2. The base64 encoded binary of the fulfillment document (the clients - if they want to do so - will generate the image themselves)


**Regarding the latter**, we understood the binary must be visible in the fulfillmentPart, using the securityFeatures array to provide the necessary details. Do you agree?


**For the image**, our first thoughts were to produce a fulfillmentDocument since the image of the barcode is used for travelling. 

**Nonetheless, we just came accross this issue and are wondering if we must produce a fulfillmentPart as well.**
This fulfillmentPart will include the binary needed to create the image (data), as well as the type, format and symbology identified as BAR_CODE + PNG + AZTEC in our case. 

While the fulfillmentDocument will contain the compulsory elements below (knowing that the content must be provided in our case since we will not have any downloadLink):
- medium = FULFILLMENT_PARTS
- type = TICKET
- format = image/png
- content = ??? looks the same as the one provided in fulfillmentParts.data
 
Thanks a lot!

**Comment by jspetrak** [comment]
@FloLhomme I suggest to open a new issue referring this one and maybe discuss it at one of Friday tech calls in the group.
